### ISSUE TITLE
Try  0

### ISSUE THREAD

**Issue by Kranzy** [maks/ginlong-lua#2]
Hi,

I am trying to implement this to work an a raspberry pi for a 5kw ginlong inverter. 

My log is showing me my api and the says try 0 and thats it. I am currently seeing no data being written to pvoutput.org.

Any assistance would be greatly appreciated.

Regards
Paul

**Comment by maks** [comment]
Via email exchange, this got sorted out, it seems the issue was that I had missed in my documentation the need to set the required settings on the serial connection (which is currently done in the `connect` shell script).
This is really somethign that should be done in the lua code so I'll open a new issue to address that.
